name:                win-fonts
version:             0.1.0.0
github:              "RowanMorrison/win-fonts"
license:             BSD3
author:              "RowanMorrison"
maintainer:          "rowanmorrison@protonmail.ch"
copyright:           "RowanMorrison"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/RowanMorrison/win-fonts#readme>

dependencies:
- base >= 4.7 && < 5
- Win32
- extra

library:
  source-dirs: src

executables:
  win-fonts-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - win-fonts

tests:
  win-fonts-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - win-fonts
